### ISSUE TITLE
Add MinGW support

### ISSUE THREAD

**Issue by Pwera** [McMartin/FRUT#228]
Add MinGW support

**Comment by McMartin** [comment]
@Pwera: thanks for opening this issue!

To help me add MinGW support, I would like you to answer the following questions:

- Which version of MinGW are you using? Where can I download it?
- Which version of JUCE are you using?
- Are you using the Code::Blocks project generated by Projucer? 
- Do you have an open-source JUCE project that you are building with MinGW?
