### ISSUE TITLE
Reprojucer.cmake doesn't support the setting DEVELOPMENT_TEAM_ID

### ISSUE THREAD

**Issue by McMartin** [McMartin/FRUT#251]
If you would like `Reprojucer.cmake` to support the setting `DEVELOPMENT_TEAM_ID` ("Development Team ID" in Projucer), please leave a comment on this issue.

**Comment by stijnfrishert** [comment]
Don't necessarily need this (signing could be done with a post-build script), but would be nice to have anyway.

**Comment by brettbuddin** [comment]
@stijnfrishert Do you have a good example of this? I'm interested in signing after I've produced my artifacts, but I can't find a whole lot of documentation on doing it in post.

**Comment by brettbuddin** [comment]
Ah figured it out. I wasn't aware of the separate `codesign` tool.

**Comment by stijnfrishert** [comment]
Yeap, that's basically it! :)

**Comment by McMartin** [comment]
@stijnfrishert, @brettbuddin: #546 is adding support for this setting. Sorry for the very long delay.
