### ISSUE TITLE
Reprojucer.cmake doesn't support building AAX plugins

### ISSUE THREAD

**Issue by McMartin** [McMartin/FRUT#267]
If you would like `Reprojucer.cmake` to support building AAX plugins, please leave a comment on this issue.

**Comment by Xav83** [comment]
One more information about AAX support.
We have updated our project to JUCE 5.2.0 and there is a difference in the way to build the AAX version with the JUCE 4.3.1.

In the version JUCE 4.3.1, we only had to build the scheme `AAXLibrary` of the solution `AAXLibrary.xcodeproj` (cf. the third step in the previous message).
In the version JUCE 5.2.0, we have to build the two schemes of the solution `AAXLibrary.xcodeproj` : the scheme `AAXLibrary` and the scheme `AAXLibrary_libcpp`

Hope this information will be helpful when you will integrate the AAX support into FRUT

**Comment by McMartin** [comment]
@Xav83 I finally took the time to work on building AAX plugins using `Reprojucer.cmake`. I made a branch: https://github.com/McMartin/FRUT/tree/wip/support-building-AAX-plugins. It's still WIP, but you should be able to build something on macOS. 
Please give me any feedback!

**Comment by Xav83** [comment]
Hi @McMartin ! Sorry for the delay !
I've tried to build our project AAX target with the branch you specified, I've encountered a bug in the Reprojucer which stopped the generation of the solution. After a little debugging, I've found the problem and corrected it. I've put the fix in a patch that I will attach to this comment.
With the fix, everything compiled correctly on the setup I have. FYI, the setup is a OSX 10.13,  Xcode 9.3 and JUCE 5.2.0. I also tried with the generator "Unix Makefiles" to compile the AAX plugin without any problem.

I hope this will help you, and if you need someone to test on Windows 10 too, don't hesitate to ask 😉 

[0001-fixup-WIP-Support-building-AAX-plugins.patch.txt](https://github.com/McMartin/FRUT/files/2050619/0001-fixup-WIP-Support-building-AAX-plugins.patch.txt)

**Comment by McMartin** [comment]
@Xav83 thank you very much for the patch, very good catch! I've amended the branch with your fix. I'll work on the missing parts for Windows soon and ping you again once it's ready for testing.

**Comment by McMartin** [comment]
@Xav83 I ended up working on the branch right away :smile: Please try the latest version of the branch (https://github.com/McMartin/FRUT/commit/b80a472e8db059926606b730c5668c2bfb6d29ab) on Windows. Thanks!
