### ISSUE TITLE
Link issue with JUCE 5.2.0

### ISSUE THREAD

**Issue by Xav83** [McMartin/FRUT#292]
Hi @McMartin !

We've recently trying to upgrade the JUCE version on our project from the version 4.3 to the version 5.2.0, and we have encountered a problem on Windows, with Visual Studio 2015.
In our project, we are building the vst and the vst3 version of our plugin, everything is compiling fine, but during the linking, an error occurs :
`include_juce_audio_plugin_client_VST3.obj : error LNK2005: _DllMain@12 already defined in include_juce_audio_plugin_client_VST2.obj`

We have tried to use the last version of the VST sdk, and then, after seing this [thread on the juce forum](https://forum.juce.com/t/no-flock-cpp-in-vst-sdk/25069/10), we have tried the sdk you've linked, without success. We had either the error described above, or some errors because of missing files that Juce is looking for while VST sdk version has moved or removed those files.

When building the project without FRUT, with Projucer, this error does not occur.

Thanks in advance for your attention, and if you need any other information about this problem, just ask 😉

**Comment by Xav83** [comment]
I forgot to mention, we've also updated the FRUT version to the current master ! 😃

**Comment by McMartin** [comment]
@Xav83 as usual, thanks a lot for the detailed bug report.

You are hitting the limitations of FRUT wrt. using JUCE 5... As mentioned on the README (https://github.com/McMartin/FRUT#requirements), JUCE 5 support is still experimental.

I am working on a branch that improves the JUCE 5 support and should fix you issue. What is your ideal time frame to switch to JUCE 5 (if you reply "yesterday", I'll try to hack down something :smile:)

**Comment by Xav83** [comment]
@McMartin You're welcome.

I knew that JUCE 5 support is still experimental, but I wanted to see if our project will work with it. 
FYI, we haven't faced any problem on OSX, well done ! 👍 
I've created this issue to be able to give you some feedback about this update attempt 😉 

Haha If you can make it happen yesterday it will be perfect 😆 
Jokes aside, don't worry, if we'd really need to go to Juce 5, we could still generate our project with the Projucer and `xcodebuild` to automate it, and switch back to FRUT, when the JUCE 5 support will be more advanced, so there is no need to rush.

If you ever need some feedback on JUCE 5 support, you can ask us (@WGuLL or myself), we will update FRUT on our repository and tell you what's working and what's broken 😉
