### ISSUE TITLE
JUCE 5.2.0 C++ standard version

### ISSUE THREAD

**Issue by Xav83** [McMartin/FRUT#297]
Hi @McMartin,

I post this issue to report you a bug with the last version of FRUT (the one on master) and JUCE 5.2.0. I've tried to integrate FRUT to a project that is using some c++14 features, and the compilation failed when reaching the c++14 code.
I've investigated a little and found that, in the CMaleLists.txt file generated by FRUT, I have the line `CXX_LANGUAGE_STANDARD "Use Default"` for the export `Xcode (MacOSX)` in Debug and Release mode. On the other project which are using only C++ 11 features, the projects compiles, but the same line `CXX_LANGUAGE_STANDARD "Use Default"` is present.

I've looked a bit further and found that in the jucer files of those projects, the C++ standard version is specified like that : `cppLanguageStandard="11"` for C++11 and cppLanguageStandard="14" for C++14, while in the FRUT Reprojucer main.cpp file, the value isn't the same ([link to the part of the source code here](https://github.com/McMartin/FRUT/blob/master/Jucer2Reprojucer/main.cpp#L1118))

I hope this will help you to have a better support of JUCE 5.2.0 ;)

PS : For the fun, I've tried the different option for the field `cppLanguageStandard` in the Projucer  of JUCE 5.2.0, there are 3 options : "C++11", "C++14" and "Use Latest". Each of them are specified in the projucer respectively by `cppLanguageStandard="11"`, `cppLanguageStandard="14"` and `cppLanguageStandard="latest"`

**Comment by Xav83** [comment]
PPS : I forgot to mention that I only tried only the Xcode.

**Comment by McMartin** [comment]
Hi @Xav83 

This "bug" is another limitation of FRUT. In JUCE 5.1.0, the C++ Language Standard setting was moved from the exporters to the project level, but FRUT doesn't know about that new setting yet. This explains why you could only find the "old" values in Jucer2Reprojucer's main.cpp.

I have a work-in-progress branch to support this new setting (https://github.com/McMartin/FRUT/compare/support-cxx-language-standard-project-setting), but it's not ready for a Pull Request yet. As a work-around, you can replace `CXX_LANGUAGE_STANDARD "Use Default"` by `CXX_LANGUAGE_STANDARD "C++14"` in you CMakeLists.txt file.

**Comment by McMartin** [comment]
@Xav83 I reworked https://github.com/McMartin/FRUT/tree/support-cxx-language-standard-project-setting, it's now in an almost final state. Feel free to try it out!

**Comment by Xav83** [comment]
Hi @McMartin 

Sorry for the late reply, I was on vacation.
I've just tried the branch `support-cxx-language-standard-project-setting` that you mentioned in your last message, on OSX with Xcode, and the project compiled well with the 3 C++ version (cppLanguageStandard="11", cppLanguageStandard="14" and cppLanguageStandard="latest").
