### ISSUE TITLE
JUCE 5.2.0 - Xcode Resource

### ISSUE THREAD

**Issue by Xav83** [McMartin/FRUT#312]
Hi @McMartin,

I post this issue to report you a bug/limitation with the last version of FRUT (the one on master, `f8aef3c`) and JUCE 5.2.0. The problem comes from the files flagged as "XCode Resource" in the Projucer. When this flag is activated, the file is placed in the subfolder `Contents/Resources` of the generated file (VST/AU/Standalone).
But the problem is that, this resources folder isn't generated with this version of JUCE and FRUT. When I use only JUCE to generate the application, this folder is generated correctly. FYI, when I've compiled our project only using JUCE, I also notice that a new folder (that wasn't here with JUCE 4.3.1) was generated in `Contents`, named `_CodeSignature`, which contains a file named `CodeResources`. This file seems to also contain information on the files tagged as `XCode Resource`, but I didn't look further what exactly it contains.
When we were using FRUT with the JUCE version 4.3.1, this folder was well generated.

As a workaround, we are moving the files that are tagged as `XCode Resource` in our post build scripts. It does the work for now.

If you need more informations, or tests on this issue, don't hesitate to ask.
I hope this will help to have a better support of JUCE 5.2.0 in FRUT.

Thanks for your time and your work 😃

**Comment by McMartin** [comment]
@Xav83 thank you very much for the bug report. I'll have a look ASAP.

**Comment by McMartin** [comment]
I found the issue and I think I fixed it on this branch: https://github.com/McMartin/FRUT/tree/fix-calling-set_source_files_properties. Please let me know whether that works for you.

**Comment by Xav83** [comment]
As you said, @McMartin , the work on this branch fixes the problem 👍
