### ISSUE TITLE
Error Building Project with CMake - CMAKE_MODULE_PATH in CMakeLists.txt not correct

### ISSUE THREAD

**Issue by PioBeat** [McMartin/FRUT#327]
Hi!

I have the following tools/frameworks installed:
- JUCE v5.2.1
- CMake 3.10.2
- Visual Studio 2017 - Version 15.6.3

The conversion of a *.jucer project to a new CMakeLists.txt file works. When building the project using CMake the following error occurs:
```
$ cmake .. -G "Visual Studio 15 2017 Win64" -DNewProject_jucer_FILE=../NewProject.jucer
-- The C compiler identification is MSVC 19.13.26129.0
-- The CXX compiler identification is MSVC 19.13.26129.0
-- Check for working C compiler: C:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    Reprojucer


CMake Error at CMakeLists.txt:22 (jucer_project_begin):
  Unknown CMake command "jucer_project_begin".


-- Configuring incomplete, errors occurred!
See also "C:/NewProject/build/CMakeFiles/CMakeOutput.log".
```

However, this error can be fixed when manually editing the generated CMakeLists.txt like this:
```
# This file was generated by Jucer2Reprojucer from "NewProject.jucer"

cmake_minimum_required(VERSION 3.4)

project("NewProject")


list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/../../../../../git/FRUT/prefix/FRUT/cmake") <----- change made here
include(Reprojucer)

[...more lines ...]
```
**I had to append the `cmake` folder to the `CMAKE_MODULE_PATH` variable.**

**My question:** Is this an actual error or can this be specfied with **Jucer2Reprojucer** (which isn't described in the README yet).

**Comment by McMartin** [comment]
Hi,

Thank you very much for creating this issue!

When calling `Jucer2Reprojucer`, you need to provide two arguments:
- the `.jucer` file you want to convert
- the path to `Reprojucer.cmake`

How did you call `Jucer2Reprojucer` exactly?

In the README, the example command is
```
$ ../FRUT/prefix/FRUT/bin/Jucer2Reprojucer MyGreatProject.jucer ../FRUT/prefix/FRUT/cmake/Reprojucer.cmake
```
where `MyGreatProject.jucer` is the `.jucer` to convert and `../FRUT/prefix/FRUT/cmake/Reprojucer.cmake` is the path to `Reprojucer.cmake` (including `Reprojucer.cmake` itself).

I guess I should add a check in `Jucer2Reprojucer` that the second argument ends with `Reprojucer.cmake` and is a file that exists.

**Comment by McMartin** [comment]
@PioBeat I merged https://github.com/McMartin/FRUT/pull/328. I hope that will help you. Feel free to close this issue if it is now solved.

**Comment by PioBeat** [comment]
Thank you for looking into this issue. The path to ``Reprojucer.cmake`` was missing exactly that part. Now the path in the ``CMakeLists.txt`` file is correct.

The change in #328 is very helpful! I will close this issue now.
