### ISSUE TITLE
XCode 9.3 - warning as error in the Reprojucer

### ISSUE THREAD

**Issue by Xav83** [McMartin/FRUT#336]
Hi @McMartin,

Five days ago, XCode has published a new release : XCode 9.3 ([Release note here](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-SW1)).
I've tried to use it with JUCE and FRUT, but sadly the Reprojucer doesn't compile with this version of XCode. FYI, previously I was using XCode 9.2 without encounter any problem.

This version of XCode triggers warnings in JUCE due missing `override` keyword on some class destructors, and the flag `Werror`.
The full config I've used to build is OSX 10.13.4, XCode 9.3, JUCE 5.2.0 and FRUT master (sha `2f8b887`)
Here is the Reprojucer xcode build output so you can look at it without having to install the last version of XCode for now - [xcode9.3 build output.txt](https://github.com/McMartin/FRUT/files/1872171/xcode9.3.build.output.txt)

I hope this will help you ! Thanks for your time and your work 😃

**Comment by McMartin** [comment]
Hi @Xav83,

Thank you very much for reporting this issue. It should be fixed by https://github.com/McMartin/FRUT/pull/337.

**Comment by Xav83** [comment]
It works great ! Thanks ! 😃
