### ISSUE TITLE
Not compiling on Linux with g++ 7.1.0

### ISSUE THREAD

**Issue by dscheffer** [McMartin/FRUT#347]
Compilation fails on Linux with g++ 7.1.0. Apparently the `-Wextra` compile flag includes the `-Wimplicit-fallthrough` flag which the juce-core module does not comply with which causes compilation to fail because of the `-Werror` flag.

I found that inserting the `-Wno-implicit-fallthrough` option [here](https://github.com/McMartin/FRUT/blob/master/Jucer2Reprojucer/CMakeLists.txt#L204-L210) solves it. Compilation with older g++ versions will probably not break either. I tried it with g++ 5.4.0 and it worked fine for this version.

BTW: I am using JUCE 5.3.2

**Comment by McMartin** [comment]
Hi @dscheffer,

Inserting `-Wno-implicit-fallthrough` in https://github.com/McMartin/FRUT/blob/master/Jucer2Reprojucer/CMakeLists.txt#L210 is what I would indeed do to "solve" that issue now. Would you like me to do the change or do you want to open a Pull Request?

FRUT doesn't support the Projucer settings introduced in JUCE 5.3+ yet (`Plugin Formats`, `Plugin Characteristics`, etc.). These settings concern only Audio Plug-In projects though, so it might not be an issue for you.

Cheers,
Alain

**Comment by dscheffer** [comment]
The problems with version 5.3+ are indeed not an issue for me right now. ;)
Other than that I submitted a pull request.

**Comment by McMartin** [comment]
Resolved by #348.
