### ISSUE TITLE
Custom AAX Binary Location

### ISSUE THREAD

**Issue by Xav83** [McMartin/FRUT#359]
Hi @McMartin 

I've finally been able to have the time to integrate FRUT with AAX support on the projects I'm working on. \o/
The AAX plugin are well generated which is great.

I've only been able to found one problem : when the AAX binary location field is specified in the jucer file (the attribute name in the jucer is `aaxBinaryLocation`), on OSX, then an error is triggered. When nothing is set in this field, everything works fine.
The exact error I had is :
```
CMake Error at cmake_install.cmake:145 (file):
  file INSTALL cannot make directory
  "/Library/Audio/$(HOME)/Library/Audio/Plug-Ins/AAX/<pluginName>.aaxplugin":
  No such file or directory
```
where `$(HOME)/Library/Audio/Plug-Ins/AAX` is the path I put in the jucer field

If you need any more tests on this issue, don't hesitate to ask 😉

**Comment by McMartin** [comment]
Hi @Xav83,

I think the problem comes from the dollar sign in `$(HOME)`. Could you confirm that by replacing `$(HOME)/` with `/Users/Xavier/` (assuming your user name is `Xavier`)?

**Comment by Xav83** [comment]
@McMartin As you asked, I've tried with an absolute path and it works well for the AAX binary location.
It works well that way, which solve my problem ! 🎆 
I don't know if you will address the `$(HOME)` case in this issue or later, so I let you close this issue if you want to handle this case later.
FYI, I've tried to replace `$(HOME)` by `~`, to make the path not depending on the username of the machine, and it triggered a cmake error :
```
CMake Error at cmake_install.cmake:98 (file):
    file INSTALL cannot set permission on "~//<plugin_name>.aaxplugin"
```
but the aaxplugin file was well created. I don't know if this problem is related to the `$(HOME)` case. I just wanted to let you know, since it concerns the same field in the jucer file.

**Comment by McMartin** [comment]
@Xav83 Thanks for trying out and confirming my theory.
Projucer supports `$(HOME)/Library/...`, so Reprojucer.cmake should support it as well.
Could you check whether Projucer also supports `~/Library/...`?

**Comment by Xav83** [comment]
I've tried it with the Projucer and also got an error with `~/Library`.

**Comment by McMartin** [comment]
[Projucer does:](https://github.com/WeAreROLI/JUCE/blob/5.3.2/extras/Projucer/Source/ProjectSaving/jucer_ProjectExport_Xcode.h#L1053-L1054)
```
            if (installPath.startsWith ("~"))
                installPath = installPath.replace ("~", "$(HOME)");
```
so using `~/Library/...` should work like using `$(HOME)/...`.

This means that Reprojucer.cmake should convert both `$(HOME)/` and `~/` into `$ENV{HOME}/` (which is the CMake way).

**Comment by Xav83** [comment]
I've tested the PR #360 and it worked well.
FYI, I looked at the line from the Projucer of your last comment to understand why it did not worked when I tried it. It seems that this code has been added in [Juce 5.2.1](https://github.com/WeAreROLI/JUCE/blob/5.2.1/extras/Projucer/Source/ProjectSaving/jucer_ProjectExport_Xcode.h#L1038), and we are using [Juce 5.2.0](https://github.com/WeAreROLI/JUCE/blob/5.2.0/extras/Projucer/Source/ProjectSaving/jucer_ProjectExport_Xcode.h#L1000) where this code isn't yet added.

**Comment by McMartin** [comment]
@Xav83 you are totally right. The code snippet I included in my previous comment was added to Projucer in https://github.com/WeAreROLI/JUCE/commit/3caca8743d1b62c8976cf9457d495e7be82c5b85, which comes after 5.2.0.
