### ISSUE TITLE
.entitlements issue

### ISSUE THREAD

**Issue by IqraShahzad1** [McMartin/FRUT#373]
Its seems so that there are successful builds with cmake, but I could not find anything to set the sandbox flag that is under the .entitlements in a project.
This means that the project can not be run inside from GarageBand. 
Also I could not find anything on .nib extensions

**Comment by McMartin** [comment]
@IqraShahzad1 

Thank you very much for creating this issue!

`Reprojucer.cmake` is not complete and still misses many features of Projucer. As you noticed, it doesn't create any `.entitlements` file yet. By looking at Projucer's code, I saw that `.entitlements` files are only used for Audio Plug-in projects. 
What kind of plugin did you try to run inside GarageBand? Was it AUv3 or another plugin format?

I made an attempt at fixing your issue on a branch named [`wip/create-entitlements-file-for-AUv3`](https://github.com/McMartin/FRUT/commit/15e01a514e156ca9df5bcfcb9de9489507f57843). I did this on Windows, so it's very likely that it won't work. I'll work on the proper solution as soon as I can get my hands on a Mac.

`Reprojucer.cmake` doesn't create any `.nib` file either. Please open another issue to discuss that separately.

**Comment by McMartin** [comment]
I finally got my hands on a Mac! I reworked that code a bit and pushed a new branch named [`wip/support-adding-entitlements-to-AUv3`](https://github.com/McMartin/FRUT/commits/wip/support-adding-entitlements-to-AUv3).

@IqraShahzad1 do you have the time and the capability to try this branch? If not, or if I don't hear from you in the coming week, I think I'll simply merge it.
