### ISSUE TITLE
AudioUnit plugin not discoverable

### ISSUE THREAD

**Issue by rclement** [McMartin/FRUT#398]
When building an AudioUnit plugin (macOS only) after generating an XCode project using FRUT, the plugin is not discoverable by AU hosts and the Apple validation tool (`auval -a` or `auval -v <type> <plugin> <manufacturer>`).

Generating the same AU plugin using the Projucer does the trick. After some digging, it seems it all boils down to an XCode "Rez" file (or "Carbon resource") not being copied (nor compiled) from JUCE:

```bash
juce/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU.r -> JuceLibraryCode/include_juce_audio_plugin_client_AU.r
```

I tried to simply modify FRUT to discover `.r` files in JUCE modules, which adds it properly only to the AU building group, in `jucer_project_module`:

```cmake
  file(GLOB module_src_files
    LIST_DIRECTORIES FALSE
    "${modules_folder}/${module_name}/${module_name}*.cpp"
    "${modules_folder}/${module_name}/${module_name}*.mm"
    "${modules_folder}/${module_name}/${module_name}*.r"
  )
```

However, something more seems to be required in order to properly build the "Rez" file (i.e. make XCode know it is a "Rez" file and not just a "Source file", add it to the AU building target, and compile it using Reztool) and add it to the final bundle `.component`.

Any ideas?

Also if there is a simple trick to bypass the Rez file all-together and make AU plugins discoverable in a deterministic fashion, this is very welcome!

**Comment by McMartin** [comment]
@rclement thanks for reporting that issue. Thank you as well for trying to fix it.

I don't have a Mac right now, but I still made a branch to try to fix the issue: [wip/support-Rez-files-in-AU-plugins](https://github.com/McMartin/FRUT/tree/wip/support-Rez-files-in-AU-plugins). I'll test that branch properly once I get my hands on a Mac, but feel free to try it out and to let me know what doesn't work.

**Comment by rclement** [comment]
@McMartin Thanks for starting a WIP branch.

I tried your branch, it does:
- Add the ".r" file to the AU target
- Generate, register and run the pre-build script

However, Rez build is failing:

```bash
/usr/bin/Rez -I <path>/JuceLibraryCode -o <path>/<plugin>.rsrc <path>/JuceLibraryCode/include_juce_audio_plugin_client_AU.r
failed to find juce_audio_plugin_client/juce_audio_plugin_client_AU.r
<path>/JuceLibraryCode/include_juce_audio_plugin_client_AU.r:2: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - SysError 2 during open of "juce_audio_plugin_client/juce_audio_plugin_client_AU.r".
Fatal Error!
<path>/JuceLibraryCode/include_juce_audio_plugin_client_AU.r:2: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - Fatal Error, can't recover.
<path>/JuceLibraryCode/include_juce_audio_plugin_client_AU.r: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - Since errors occurred, <path>/<plugin>.rsrc's resource fork was not written.
make: *** [<plugin>_AU_buildpart_0] Error 3
```

As `<juce_audio_plugin_client/juce_audio_plugin_client_AU.r>` is expected to be found, I tried adding the JUCE modules folder to the search path:

```cmake
        set(all_search_path_modules ${JUCER_PROJECT_MODULES_FOLDERS})
        list(REMOVE_DUPLICATES all_search_path_modules)
        set(rez_search_path_modules "")
        foreach(module_folder ${all_search_path_modules})
          list(APPEND rez_search_path_modules "-I" "${module_folder}")
        endforeach()

        add_custom_command(TARGET ${au_target} PRE_BUILD
          COMMAND
          "${Rez_exe}"
          "-I" "${CMAKE_CURRENT_BINARY_DIR}/JuceLibraryCode"
          ${rez_search_path_modules}
          "-o" "${rez_output}"
          "${rez_sources}"
        )
```

The command is generated properly but it still does not work.

**Comment by rclement** [comment]
@McMartin I submitted PR #399 which should fix the Rez file build.

I tested the fix on my own plugin several times, it works on my end.
The AU plugin is now automagically discoverable with `auval` and AU hosts, and passes the full validation.

Please do not hesitate to clean things up, I'm no CMake-expert.

**Comment by McMartin** [comment]
@rclement I got my hands on a Mac and fixed the remaining issues on my branch. Feel free to give it another try.

**Comment by rclement** [comment]
@McMartin Wow, you're a CMake wizard! Thanks!
