### ISSUE TITLE
Release builds set to -march=native on Linux, making them incompatible with many machines

### ISSUE THREAD

**Issue by scotchi** [McMartin/FRUT#426]
https://github.com/McMartin/FRUT/blob/282f7204f3bada25ea411e209180a4fa2384de20/cmake/Reprojucer.cmake#L1358

It seems almost certainly wrong to use `-march=native` on release builds since it stands to reason that portable binaries are desired.   Before realizing that FRUT was adding this flag, I spent several hours tracking down why VSTs built on my Linux desktop with this were crashing on startup when I installed the packages on my laptop.  Specifically, the default x86-64 should probably not be overridden.

**Comment by McMartin** [comment]
I've just realized that passing `<None>` to `jucer_export_target_configuration` still leads to `-march=native` being passed to the compiler. That's a bug, I'm sorry about that. I think applying the following diff would solve the issue:
```diff
diff --git a/cmake/Reprojucer.cmake b/cmake/Reprojucer.cmake
index 7ad27c96..55b15f0d 100644
--- a/cmake/Reprojucer.cmake
+++ b/cmake/Reprojucer.cmake
@@ -1364,7 +1364,9 @@ function(jucer_export_target_configuration
       set(architecture_flag "-march=armv6")
     elseif(architecture STREQUAL "ARM v7")
       set(architecture_flag "-march=armv7")
-    elseif(NOT architecture STREQUAL "<None>")
+    elseif(architecture STREQUAL "<None>")
+      set(architecture_flag "")
+    else()
       message(FATAL_ERROR "Unsupported value for ARCHITECTURE: \"${architecture}\"")
     endif()
     set(JUCER_ARCHITECTURE_FLAG_${config} "${architecture_flag}" PARENT_SCOPE)
```

**Comment by scotchi** [comment]
It still seems to be a very odd choice for a release build.  On Linux, `-march=native` will produce binaries that won't run on other CPUs from the same family -- in this case, my Intel Core i5 (x86-64) desktop produces binaries that my netbooks Intel Pentium N3700 (also x86-64) can't run.  It's basically an unacceptable flag to use on binaries that will be redistributed, and an odd thing to go out of the way to set.  (Unlike on Windows or macOS where the "native" platform has a much broader definition and will be compatible with other machines in the same family.)

**Comment by scotchi** [comment]
Oh, and the way I ended up working around it was just with:

`set(JUCER_ARCHITECTURE_FLAG_Release "-march=x86-64")`

**Comment by McMartin** [comment]
> It still seems to be a very odd choice for a release build. 

`-march=native` enables all optimizations for the current compiler, so it does makes sense for a release build. However, you are totally right, it shouldn't be used for binaries that will be redistributed.

Doing `set(JUCER_ARCHITECTURE_FLAG_Release "-march=x86-64")` is indeed a very good workaround!

**Comment by scotchi** [comment]
I won't drag this out much longer, but what use case do you imagine for "-march=native" for release builds?  The only two I can think of are open source packages for source-based Linux distributions (like Gentoo) or deploying server code via source (which seems possible with JUCE, but rather unlikely).

Those seem like far more obscure use cases than building of packages for open source or proprietary desktop apps (which seems like what the main use of JUCE is).  I still can't get my head around why something should be enabled by default that almost everyone will need to discover and turn off.

**Comment by McMartin** [comment]
> what use case do you imagine for "-march=native" for release builds? 

In the context of high performance trading or very CPU intensive simulations, almost all applications. In the context of audio applications and plugins, none indeed. 

> I still can't get my head around why something should be enabled by default that almost everyone will need to discover and turn off.

I can't give you any answer, because I didn't make that choice. The JUCE team did. `Reprojucer.cmake` is here to reproduce the behavior of `Projucer`. I know this is quite frustrating for you since you stopped using `Projucer` for quite some time and just want CMake support. Please bear with me, I'm working on a `FindJUCE.cmake` module that will allow us to write `find_package(JUCE ...)`. It will provide only the necessary files, include directories and preprocessor definitions, and you will have all the freedom you want in terms of compiler flags.

**Comment by scotchi** [comment]
Yeah, I didn't mean to imply that there's never a use for `-march=native` (I use it myself in projects that are deployed to servers via source), just that it seemed an odd choice a default for desktop audio apps.  I may consider filing a bug with JUCE.  :-)
