### ISSUE TITLE
/LTCG linker option does not turned on in Visual Studio when building a library.

### ISSUE THREAD

**Issue by czyjerry** [McMartin/FRUT#491]
This happens either when I'm using a default Link-Time Optimisation, or when I enable it explicitly.
Can you check this out?
Thank you!

**Comment by czyjerry** [comment]
Hi! I just found that in a APP project, this issue also exists.
The /GL compile option is in there in release configuration, but the /LTCG linker option is not in there.
This cause every JUCE based and FRUT generated Visual Studio project have linker warning:

> MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance

when building with Release configuration.

**Comment by McMartin** [comment]
@czyjerry thank you very much for reporting this bug and for providing all that valuable information! It shouldn't be too hard to fix.

**Comment by czyjerry** [comment]
Thanks for the fix!
This fix the issue in all the stanalone app projects, and dynamic library projects.
But I found that this issue still exists in static library projects.
Can you check it again?

Thanks!
