### ISSUE TITLE
/LTCG linker option does not turned on in Static Library projects

### ISSUE THREAD

**Issue by czyjerry** [McMartin/FRUT#494]
This is a remaining problem for issue: #491 after pull request: #492 
The detail of this issue is also stated in the issue and pull request mentioned above.

> Thanks for the fix!
> This fix the issue in all the stanalone app projects, and dynamic library projects.
> But I found that this issue still exists in static library projects.
> Can you check it again?
> 
> Thanks!

**Comment by McMartin** [comment]
@czyjerry thank you very much for opening this issue! I'm sorry for trying to solve #491 too fast with #492 and in the end missing almost half of the fix...

**Comment by czyjerry** [comment]
This runs perfectly!
Now all types of JUCE based project can have this /LTCG linker flag in Release configuration.
Thank you very much!
