### ISSUE TITLE
FRUT caused Visual Studio to generate LNK1104 linker error when adding extra linker flags to Projucer‘s Visual Studio exporter

### ISSUE THREAD

**Issue by czyjerry** [McMartin/FRUT#507]
I met a problem here.
When I add a extra linker flag "\ignore:4049" to Projucer‘s Visual Studio exporter, and build the Visual Studio solution generated by FRUT and CMake, the VS generates a fatal link error: "LINK : fatal error LNK1104: cannot open file '\ignore:4049.obj'".
Obviously, there is something wrong with FRUT parsing the extra linker flag incorrectly.
So can you fix it?
Thanks!

**Comment by McMartin** [comment]
`\ignore:4049` is not a valid linker flag, but I guess you actually passed `/ignore:4049`.
CMake treats the forward slash (`/`) as a path separator and thinks that you are specifying a path to a library to link.
MSVC accepts both a forward slash (`/`) and a dash (`-`) as an option specifier, so you could write `-ignore:4049` instead.
I guess `Reprojucer.cmake` could "be smart" and replace the forward slash (`/`) with a dash (`-`) when the item starts with a forward slash and doesn't contain another one (when using MSVC only). Or maybe `Jucer2Reprojucer` should do that.
Let me know if there is a solution your prefer.

**Comment by czyjerry** [comment]
Oh yes, I was using "/ignore:4049". And I have tested using "-ignore:4049" instead, and everythings fine.
Since my problem has been solved by such a "workaround" kind of approach, it's fine if you don't have time to deal with this conversion. However, such problems may also cause problems for other people, so I personally recommend doing this conversion in FRUT (either in Reprojucer.cmake or in Jucer2Reprojucer, both are fine for me, it's up to you to decide).

**Comment by McMartin** [comment]
I've reworded the title of the issue to change it from a problem report to an idea for improvement. I don't know when I will work on this though.

**Comment by czyjerry** [comment]
> I've reworded the title of the issue to change it from a problem report to an idea for improvement. I don't know when I will work on this though.

Awesome!  That couldn't be better!  Many thanks!

**Comment by McMartin** [comment]
I've reworded the title of the issue back to what it was originally and I re-labeled the issue, because it is indeed a bug in how `Reprojucer.cmake` is passing the "Extra Linker Flags" to CMake.
It should be fixed by https://github.com/McMartin/FRUT/pull/591.
