### ISSUE TITLE
Static libraries in JUCE modules don't end up in the linker flags

### ISSUE THREAD

**Issue by TheSlowGrowth** [McMartin/FRUT#517]
I have a JUCE module `myJuceModule` that contains static libraries (according to the JUCE module header documentation). I have a project `myProject` that uses this module. It works just fine when using the Projucer. 

When I migrate  `myProject` with `Jucer2Reprojucer` the static libraries from `myJuceModule` don't end up in the "Other Linker Flags" setting in XCode. Include paths are fine and the module is actually build. But obviously it fails at the linker stange where the symbols from the static libraries are missing.

**Comment by McMartin** [comment]
Hi @TheSlowGrowth,

Thank you for opening this issue! 

`Reprojucer.cmake` doesn't support the JUCE Module Format completely, and I'm usually adding missing parts when someone asks for them (for instance, support for the `searchpaths` setting was added in https://github.com/McMartin/FRUT/pull/449 after being requested in https://github.com/McMartin/FRUT/issues/448). 

I don't know when exactly I'll be able to work on this, but I'll try to get at least a WIP branch by the end of the week. Stay tuned!
