### ISSUE TITLE
CXX_LANGUAGE_STANDARD is not migrated by `Jucer2Reprojucer`

### ISSUE THREAD

**Issue by TheSlowGrowth** [McMartin/FRUT#518]
I converted an existing project with `Jucer2Reprojucer`. The CXX_LANGUAGE_STANDARD is not migrated and appears as an empty, commented-out setting in the generated CMakeLists.txt.

**Comment by McMartin** [comment]
Hi @TheSlowGrowth,

Thank you for using FRUT and opening this issue!

Based on what you described, I guess you set `C++ Language Standard` to `C++17` in Projucer, but `Jucer2Reprojucer` doesn't know that it is a valid value and converts it to the empty string:
https://github.com/McMartin/FRUT/blob/e7e05281d8d3be58918da7817c6b987f19e31230/Jucer2Reprojucer/main.cpp#L697-L711

However, `Reprojucer.cmake` can handle `C++17`:
https://github.com/McMartin/FRUT/blob/e7e05281d8d3be58918da7817c6b987f19e31230/cmake/Reprojucer.cmake#L140-L141

It seems that I forgot to change `Jucer2Reprojucer` in https://github.com/McMartin/FRUT/pull/376/commits/1fe5686cb08edf508b6999ff5d200bc0a51c2ea0. 

Feel free to contribute a fix by opening a Pull Request with the appropriate change in `Jucer2Reprojucer`.
