### ISSUE TITLE
failing because of wrong compiler ?

### ISSUE THREAD

**Issue by dizketto** [McMartin/FRUT#560]
```
CMake Error at CMakeLists.txt:20 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.
```
same thing for the _C_ compiler.  Same error. Am I wrong to think it's trying to use MSVC compiler by default ?

**Comment by dizketto** [comment]
Rectification: don't try to build inside git bash on Windows!
Building from the cmd shell works fine.
Sorry for the fuss.

**Comment by dizketto** [comment]
Ok.. now is going ok but when I try to generate the Makefiles for my project I get
CMake Error at E:/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:1983 (message):
  You must call jucer_export_target("Code::Blocks (Windows)") before calling
  jucer_project_end().

**Comment by McMartin** [comment]
Hi @dizketto,

Thanks for using FRUT! 

I'm currently at a party where @MartyLake (who reviews all PRs of FRUT) is playing some French House (see https://martylake.com if you're interested), so I don't have a lot of time to help you, but you can read more about the error you are getting here: https://github.com/McMartin/FRUT/issues/463.

I hope this helps!

**Comment by McMartin** [comment]
Hi @dizketto,

I'm back home after a very busy week in Berlin. I now have more time to help you use FRUT. 
Please let me know if you are still facing some problems. Otherwise, I'll close this issue at the beginning of next week. Thanks!
