### ISSUE TITLE
Rez error compiling AU with Xcode 11.2.1 / OSX 10.15 SDK

### ISSUE THREAD

**Issue by dimitrisudell** [McMartin/FRUT#562]
Hello,

I've been assessing FRUT for my current project. Everything has been going great until I tried to build AUs with Xcode 11.2.1 / OSX 10.15 SDK. Compilation fails with the following error.

`### Rez - noErr (0) during open of "AUComponent.r". AudioUnit.r`

I compared the Cmake file Projucer creates using the Clion exporter and noticed there are some differences in the Rez command.

The critical difference seems to be the header search directories. When I add the following line to the FRUT generated Rez command everything compiles successfully. 

Rez command - https://github.com/McMartin/FRUT/blob/43b41ccfdd0fd1789b0f9fad2310d5ea38e46849/cmake/Reprojucer.cmake#L2990

Additional search directory -
`"-i" "$(DEVELOPER_DIR)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AudioUnit.framework/Headers"`

Thanks,
Dimitri.

**Comment by McMartin** [comment]
Hi @dimitrisudell,

Thanks for giving a try to FRUT!

It will take me a bit of time to get my hands on a machine that runs macOS Catalina with Xcode 11.2, but I'll try to get to the bottom of this issue in a timely manner. To speed-up my investigation, could you please run the following command and give me the result?
```
find /Applications/Xcode.app/Contents/Developer/ -name "AudioUnit*.r" -or -name "AU*.r"
```
Thanks!

**Comment by dimitrisudell** [comment]
Hey Alain,

Thanks a lot for your fast feedback.

You don't actually have to be running macOS Catalina, just the latest Xcode which includes the OSX 10.15 SDK.

I am running OSX 10.14.6 and Xcode 11.2.1.

Here is the result of running the find command. Please let me know if I can do anything else to help.

```
/Applications/Xcode.app/Contents/Developer//Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AudioUnit.framework/Versions/A/Headers/AudioUnitCarbonView.r
/Applications/Xcode.app/Contents/Developer//Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AudioUnit.framework/Versions/A/Headers/AUComponent.r
/Applications/Xcode.app/Contents/Developer//Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AudioUnit.framework/Versions/A/Headers/AudioUnit.r
```

**Comment by McMartin** [comment]
I got my hands on a macOS Catalina machine anyway :smile: 
I was then able to compare `AudioUnit.r` between the `macosx10.14` and `macosx10.15` SDKs:
```diff
--- D:\dev\tmp\compare-AudioUnit.r\macosx10.14\AudioUnit.r  Fri Nov  8 20:01:40 2019
+++ D:\dev\tmp\compare-AudioUnit.r\macosx10.15\AudioUnit.r  Fri Dec  6 11:51:29 2019
@@ -15,13 +15,8 @@
 #ifndef __AUDIOUNIT_R__
 #define __AUDIOUNIT_R__
 
-#ifndef __COREAUDIO_USE_FLAT_INCLUDES__
-   #include <AudioUnit/AUComponent.r>
-   #include <AudioUnit/AudioUnitCarbonView.r>
-#else
-   #include "AUComponent.r"
-   #include "AudioUnitCarbonView.r"
-#endif
+#include "AUComponent.r"
+#include "AudioUnitCarbonView.r"
 
 #endif /* __AUDIOUNIT_R__ */
  ```

Since `__COREAUDIO_USE_FLAT_INCLUDES__` was _not_ defined, the include behavior between the 10.14 and 10.15 SDKs changed, and indeed we need `/System/Library/Frameworks/AudioUnit.framework/Headers` in the include search path.

I'll work on adding it ASAP.

**Comment by McMartin** [comment]
@dimitrisudell I pushed a branch with a tentative fix: [`fix-running-Rez-with-macosx10.15-SDK`](https://github.com/McMartin/FRUT/tree/fix-running-Rez-with-macosx10.15-SDK). Could you please give it a try and let me know whether that fixes your issue? Thanks!

**Comment by dimitrisudell** [comment]
@McMartin I've just tried that branch out on a few different machines and all look to be working correctly now. 👍
