### ISSUE TITLE
FRUT doesn't consistently find `buildXXX` settings in recent JUCE 5 jucer files

### ISSUE THREAD

**Issue by danra** [McMartin/FRUT#566]
Looks like only some of the code was updated to handle recent JUCE 5 jucer files which puts the `buildXXX` settings under `pluginFormats` rather than under the root properties of the project.

This causes, for example, building the AAX format with the resulting converted `CMakeLists.txt` file to fail, because the AAX SDK folder never gets written into the file, because the following condition is `false`.

https://github.com/McMartin/FRUT/blob/40e96f764e9139033cc1a3b3558ced4c81188a0d/Jucer2Reprojucer/main.cpp#L1436

**Comment by McMartin** [comment]
@danra thanks a lot for trying out FRUT and for reporting this bug. I'll try to fix it ASAP. Feel free to open a PR with a fix if you want.

**Comment by danra** [comment]
I'll wait for the fix. Thank you!
