### ISSUE TITLE
Jucer2Reprojucer fails to parse defines with spaces

### ISSUE THREAD

**Issue by danra** [McMartin/FRUT#572]
Setting a `JUCERPROJECT`'s `defines` field as `defines="X = 1"` (note the spaces) isn't parsed correctly by Jucer2Reprojucer - it gets interpreted as `-DX` and `-D1`, separately.
This causes the build to fail since `#define 1 1` doesn't (pre-)compile.

**Comment by McMartin** [comment]
Good catch!

IIRC, `Reprojucer.cmake` doesn't handle this case properly because the help text in Projucer says
> Use the form "NAME1=value NAME2=value"

But Projucer still supports having spaces before and after the equal sign, so `Reprojucer.cmake` should do the same.
