### ISSUE TITLE
Error building with Ninja generator on Mac with deployment target of 10.8

### ISSUE THREAD

**Issue by danra** [McMartin/FRUT#581]
Building projects with a deployment target of 10.8 works fine with the Xcode Generator now that #569 is resolved, but still doesn't when using the Ninja generator.

This is reproducible with JUCE's demo projects (I tested `DemoRunner`), regardless of the built format(s). The Ninja generator starts building fine once you set the deployment target to 10.9 or higher.

The build error messages (at the final link command) are:
```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by McMartin** [comment]
Hi @danra,

Thanks for reporting this issue!

https://github.com/McMartin/FRUT/issues/569 was incomplete, I opened https://github.com/McMartin/FRUT/pull/582 to fix this issue.
