### ISSUE TITLE
Setting "Strip Local Symbols" in Projucer causes ninja build to fail

### ISSUE THREAD

**Issue by danra** [McMartin/FRUT#583]
Looks like instead of the strip command, the final link command gets appended with a `cd` to the `build` folder followed by `""`, instead of the strip command, which errors out. 

Reproducible by generating a clean Audio Plug-in with the Projucer and turning on Strip Local Symbols in the Release configuration.

Seems to work fine with the Xcode generator.

**Comment by McMartin** [comment]
Thank you so much for discovering and reporting all these bugs! I'll work on a fix ASAP.

**Comment by McMartin** [comment]
This issue should be fixed by https://github.com/McMartin/FRUT/pull/584.

**Comment by danra** [comment]
Fixed indeed. Thank you!
