### ISSUE TITLE
Include Boost headers directory 

### ISSUE THREAD

**Issue by julius-richter** [McMartin/FRUT#585]
Hello there, 

I want to include the Boost libraries in my Juce application. By default, the Boost libraries are located in `/usr/local/Cellar/boost`. Since I just want to use the Boost headers only, I simply need to include the include directory. In the [CMake documentation](https://cmake.org/cmake/help/latest/module/FindBoost.html) I found the following:

> Example to find Boost headers only:
> 
> ```
> find_package(Boost 1.36.0)
> if(Boost_FOUND)
>   include_directories(${Boost_INCLUDE_DIRS})
>   add_executable(foo foo.cc)
> endif()
> ```

Therefore I added

```
find_package(Boost REQUIRED)
include_directories(${Boost_INCLUDE_DIRS})
```

before `jucer_project_begin()` to the `CMakeLists.txt`.

Now in my application, I want to include `boost/numeric/ublas/matrix_sparse.hpp`. However, while compiling I get the fatal error:

```
[  4%] Building CXX object CMakeFiles/BeatTracker.dir/Source/SpectrogramComponent.cpp.o
/Users/juliusrichter/Documents/Uni/Masterarbeit/beat_tracker/app/BeatTracker/Source/SpectrogramComponent.cpp:8:10: fatal error: 'boost/numeric/ublas/matrix_sparse.hpp' file not found
#include <boost/numeric/ublas/matrix_sparse.hpp>
```

The full code can be found here: [https://github.com/julius-richter/beat_tracker/tree/master/app/BeatTracker](https://github.com/julius-richter/beat_tracker/tree/master/app/BeatTracker)

**Comment by McMartin** [comment]
Hi Julius,

What you did in the `CMakeLists.txt` seems totally valid, so I don't understand why it doesn't work... 

You could maybe add
```cmake
message(STATUS "Boost_INCLUDE_DIRS = ${Boost_INCLUDE_DIRS}")
```
to verify that `Boost_INCLUDE_DIRS` is what you expect.

You could also use a more Modern CMake approach, similar to what you did with Torch:
```diff
@@ -12,7 +12,6 @@
 find_package(Torch REQUIRED)
 
 find_package(Boost REQUIRED)
-include_directories(${Boost_INCLUDE_DIRS})
 
 
 set(BeatTracker_jucer_FILE
@@ -235,4 +234,4 @@
 
 jucer_project_end()
 
-target_link_libraries(BeatTracker PRIVATE torch)
+target_link_libraries(BeatTracker PRIVATE torch Boost::headers)
```

I hope this helps!

**Comment by julius-richter** [comment]
Thank you Alain for your quick answer!

I changed the code according to your suggestions. However, I still get the same error.

The message outputs `Boost_INCLUDE_DIRS = /usr/local/include` which is a existing path as you can see from the terminal copy:

```
juliusrichter@JuliusRichter:/usr/local/include/boost/numeric/ublas$ ls
assignment.hpp		hermitian.hpp		operation		tensor.hpp
banded.hpp		io.hpp			operation.hpp		traits
blas.hpp		lu.hpp			operation_blocked.hpp	traits.hpp
detail			matrix.hpp		operation_sparse.hpp	triangular.hpp
doxydoc.hpp		matrix_expression.hpp	operations.hpp		vector.hpp
exception.hpp		matrix_proxy.hpp	storage.hpp		vector_expression.hpp
experimental		matrix_sparse.hpp	storage_sparse.hpp	vector_of_vector.hpp
expression_types.hpp	matrix_vector.hpp	symmetric.hpp		vector_proxy.hpp
functional.hpp		opencl			tags.hpp		vector_sparse.hpp
fwd.hpp			opencl.hpp		tensor
```

Any other ideas how to solve this problem?

**Comment by McMartin** [comment]
You could build with verbosity to see what the exact compiler command line is using:
```
$ cmake --build . -v
```
or
```
$ VERBOSE=1 make
```

**Comment by julius-richter** [comment]
@McMartin Thank you for the hint.

Actually, I solved the problem by including the absolute path of the boost include directory to the CMakeLists.txt. It is not very elegant, however, it works for the moment. 

```
find_package(Boost REQUIRED)

if(Boost_FOUND)
  include_directories(BEFORE "/usr/local/Cellar/boost/1.72.0/include")
endif()
```

**Comment by McMartin** [comment]
If it works, great!
