### ISSUE TITLE
Jucer2Reprojucer generates an absolute folder path

### ISSUE THREAD

**Issue by eyalamirmusic** [McMartin/FRUT#598]
Calling Jucer2Reprojucer sets the jucer file path to an absolute folder, rather than relative.

The result looks like that:
set(SpecialEffect_jucer_FILE
  "/Users/eyalamir/Code/JUCECmakeRepoPrototype/Plugins/SpecialEffect/SpecialEffect.jucer"
)

To reproduce, clone this demo repo:
https://github.com/eyalamirmusic/JUCECmakeRepoPrototype

And look at the generated CMakeLists.txt in any of the plugins under "Plugins".

**Comment by McMartin** [comment]
@eyalamirmusic 

Thanks a lot for using FRUT!

Currently, when you give an absolute path for the `.jucer` file to `Jucer2Reprojucer`, it writes it as-is in the generated `CMakeLists.txt` file. This means that calling `Jucer2Reprojucer /absolute/path/to/project.jucer` and `Jucer2Reprojucer project.jucer` don't result in the same `CMakeLists.txt` file. I should maybe fix that.

Let me know what you think about it. Thanks!

**Comment by eyalamirmusic** [comment]
Thanks! Yeah, ideally it would either write it in the working directory, or where JUCER is unless you explicitly specify some other folder...

**Comment by McMartin** [comment]
Assuming that the `CMakeLists.txt` file and the `.jucer` files are in the same directory doesn't work. For instance, FRUT contains a lot of `CMakeLists.txt` files (under [`generated/`](https://github.com/McMartin/FRUT/tree/master/generated)) to build the `examples` and `extras` from JUCE. Obviously these `CMakeLists.txt` files are not in the same directory as their corresponding `.jucer` file.

Always using a relative path to the `.jucer` file in the generated `CMakeLists.txt` file is doable (except when they are not on the same drive on Windows though 😅) and indeed makes sense. I'll work on changing that in `Jucer2Reprojucer` in the near future.

**Comment by McMartin** [comment]
@eyalamirmusic I've opened #608 to resolve this issue. Could you please confirm me that it works for you? Thanks!
