### ISSUE TITLE
Use FRUT to build directly from CMake

### ISSUE THREAD

**Issue by widmoser** [McMartin/FRUT#607]
I would like to use FRUT together with CLion. CLion directly consumes cmake files and builds them. Is there a way to use FRUT to build the final artefacts (e.g. vst3, Standalone binary) directly from CMake?

**Comment by McMartin** [comment]
Hi @widmoser,

Thanks a lot for your interest in FRUT!

> I would like to use FRUT together with CLion.

I personally don't use CLion, but I know that many people are using FRUT with CLion, and I've heard that it is great! Let me know if you need help to get started.

> Is there a way to use FRUT to build the final artefacts (e.g. vst3, Standalone binary) directly from CMake?

Yes, this is exactly what FRUT allows you to do. You should try to follow the "Getting started" steps (https://github.com/McMartin/FRUT#getting-started) with an Audio Plug-In project of yours and see how it works.
