### ISSUE TITLE
How do I link libraries or add sources

### ISSUE THREAD

**Issue by OleksandrMatasovGL** [McMartin/FRUT#610]
I don't see any "add_executable". The generated code looks alien and uses own syntax.

* What target do I use to link to the library and how to do it, what is the target? Most important question.
* How do I add new source files? I see the table with source files - tried to add entries without success.

**Comment by McMartin** [comment]
Hi @OleksandrMatasovGL,

Thanks a lot for giving a try to FRUT!

`Reprojucer`, as its name suggests, is a CMake module that reproduces what Projucer does. `Reprojucer` provides [several commands](https://frut.readthedocs.io/en/latest/Reprojucer.cmake/index.html#commands) and most of them correspond to a setting panel in Projucer. So depending on how familiar your are with Projucer, the generated `CMakeLists.txt` file might indeed look alien.

[`jucer_project_end`](https://frut.readthedocs.io/en/latest/Reprojucer.cmake/command/jucer_project_end.html) is the command that creates the target(s) by calling `add_executable` and/or `add_library`. The target name is not explicitly written anywhere in the generated `CMakeLists.txt` file (I guess I should work on that), it is derived from the `PROJECT_NAME` passed to `jucer_project_settings` (which matches what Projucer does).

You can find the name of the target(s) using the usually CMake ways (opening the IDE project, or running `make help` or `ninja -t list`, depending on the native build system you are using).

You can add new source files with `jucer_project_files` or with `target_sources`. When using `jucer_project_files`, you need to make sure that you put `x` and `.` in the right "columns". You can have a look at the [`CMakeLists.txt` file for `AudioPluginHost` from JUCE 5.4.7](https://github.com/McMartin/FRUT/blob/ca32bdcfb5490d13a5d689882b55ff10d6127b4e/generated/JUCE-5.4.7/extras/AudioPluginHost/CMakeLists.txt#L40-L66) for a good example.

I guess you were originally looking for a CMake module that would allow you to build JUCE projects in a proper CMake way, such as a `FindJUCE.cmake` module. I can totally understand that `Reprojucer` is disappointing in that regard. However, I'm working on a `FindJUCE.cmake` module, which is currently in an alpha state, and I will add it to FRUT at some point, once I find it good enough.

I hope this helps! Don't hesitate to ask me more questions, either here, on the JUCE forum, or on the Discord server of The Audio Programmer.

**Comment by OleksandrMatasovGL** [comment]
Thank you! Keep going!
