### ISSUE TITLE
Mac 10.10 and 10.9 builds do not work when compiled with 10.15 SDK

### ISSUE THREAD

**Issue by mhetrick** [McMartin/FRUT#612]
Hello! This was a bug fixed in JUCE 5.4.6: https://forum.juce.com/t/plug-in-built-with-xcode-11-fails-to-load-on-yosemite-10-10/35912

Essentially, to fix this, the AudioUnit framework needs to be linked before AudioToolbox. In my FRUT-generated XCode project, I see this:

`OTHER_LDFLAGS = (
					"-bundle",
					"-Wl,-headerpad_max_install_names",
					"\"/Users/tricky/Code/uamaster/projects/byome/build/Release/libUnfiltered Audio Byome.a\"",
					"-L/Users/tricky/Code/uamaster/uasdk/BXLicenser/Lib/Mac",
					"-lBXLicenser",
					"-framework",
					Accelerate,
					"-framework",
					AudioToolbox,
					"-framework",
					AudioUnit,
					"-framework",
					Carbon,
					"-framework",
					Cocoa,
					"-framework",
					CoreAudio,
					"-framework",
					CoreAudioKit,
					"-framework",
					CoreMIDI,
					"-framework",
					DiscRecording,
					"-framework",
					DiskArbitration,
					"-framework",
					IOKit,
					"-framework",
					OpenGL,
					"-framework",
					QuartzCore,
					"-framework",
					WebKit,
				);
`

It looks like AudioToolbox is getting linked first. I just tested this with JUCE 5.4.7 and the latest FRUT.

**Comment by McMartin** [comment]
Hi @mhetrick,

Thanks a lot for using FRUT and for opening this issue!

I indeed didn't reproduce the changes made to Projucer in https://github.com/WeAreROLI/JUCE/commit/997b217179bc5b60e13fb78853ff9839dfcd664c to Reprojucer yet. I'll get to it ASAP!

**Comment by McMartin** [comment]
I made a branch called [`fix-linking-against-AudioUnit-when-using-10.15-SDK`](https://github.com/McMartin/FRUT/tree/fix-linking-against-AudioUnit-when-using-10.15-SDK) and opened https://github.com/McMartin/FRUT/pull/613 to fix this issue.

@mhetrick could you please test with these changes? Thanks!

**Comment by mhetrick** [comment]
@McMartin Great, thank you! I'll be working tomorrow and I will send a beta build to the affected user. I'll write back to you if it works successfully for him.

**Comment by mhetrick** [comment]
@McMartin Great news, I can confirm that this fixed the issue that the user was having. Thank you for your help!
