### ISSUE TITLE
Support JUCE 6

### ISSUE THREAD

**Issue by timuraudio** [McMartin/FRUT#623]
Juce 6 replaces AppConfig.h with JucePluginDefines.h. It would be great if this would be supported in FRUT.

**Comment by McMartin** [comment]
I opened https://github.com/McMartin/FRUT/pull/624 to support generating the `JucePluginDefines.h` header.

@timuraudio please let me know whether that addresses your issue as expected. Thanks!

**Comment by adamski** [comment]
Just out of interest, would using FRUT provide a shortcut to converting a Projucer-based project to JUCE 6 CMake (in this case not a plugin), and/or would it require some manual work?

**Comment by McMartin** [comment]
@adamski FRUT doesn't provide such feature yet, but will soon. Stay tuned!

**Comment by jjo148** [comment]
I can see that JucePluginDefines.h is generated now, but the file is not copied into CMake's build directory and the AU target throws a fatal error because Rez cannot find the file. (Build succeeds after manually copying the file from JuceLibraryCode into build folder)

**Comment by McMartin** [comment]
@jjo148 `Reprojucer.cmake` only generates files in the CMake build directory, so I guess the `JucePluginDefines.h` file that you see is the one written by Projucer. https://github.com/McMartin/FRUT/pull/624 hasn't been merged yet, so unless you did a Git checkout of the branch `generate-JucePluginDefines-header`, `Reprojucer.cmake` doesn't generate the `JucePluginDefines.h` yet.

I'll rebase https://github.com/McMartin/FRUT/pull/624 and get it merged ASAP.
