### ISSUE TITLE
iOS Build Warning and Error

### ISSUE THREAD

**Issue by mhetrick** [McMartin/FRUT#635]
Hello, I just generated an iOS project using the command
`cmake -G \"Xcode\" -DCMAKE_SYSTEM_NAME=iOS ..`

When generating the project, I get a FRUT warning:

> CMake Warning at /Users/tricky/Code/uamaster/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:3269 (message):
>   JUCER_VST_LEGACY_SDK_FOLDER is not defined.  You should give
>   VST_LEGACY_SDK_FOLDER when calling jucer_export_target("Xcode (iOS)").
> Call Stack (most recent call first):
>   /Users/tricky/Code/uamaster/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:2168 (_FRUT_check_SDK_folders)
>   CMakeLists.txt:93 (jucer_project_end)

When building the project, I get an error with a missing AudioUnit framework during the linking stage:

> 
> Ld iosbuild/Debug-iphonesimulator/Unfiltered\ Audio\ Bass\ Mint.appex/Unfiltered\ Audio\ Bass\ Mint normal x86_64
>     cd /Users/tricky/Code/uamaster/projects/lowsat
>     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-ios9.3-simulator -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -L/Users/tricky/Code/uamaster/projects/lowsat/iosbuild/Debug-iphonesimulator -F/Users/tricky/Code/uamaster/projects/lowsat/iosbuild/Debug-iphonesimulator -filelist /Users/tricky/Code/uamaster/projects/lowsat/iosbuild/Unfiltered\ Audio\ Bass\ Mint.build/Debug-iphonesimulator/Unfiltered_Audio_Bass_Mint_AUv3_AppExtension.build/Objects-normal/x86_64/Unfiltered\ Audio\ Bass\ Mint.LinkFileList -dead_strip -Xlinker -object_path_lto -Xlinker /Users/tricky/Code/uamaster/projects/lowsat/iosbuild/Unfiltered\ Audio\ Bass\ Mint.build/Debug-iphonesimulator/Unfiltered_Audio_Bass_Mint_AUv3_AppExtension.build/Objects-normal/x86_64/Unfiltered\ Audio\ Bass\ Mint_lto.o -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -stdlib=libc++ -fobjc-link-runtime -bundle -Wl,-headerpad_max_install_names /Users/tricky/Code/uamaster/projects/lowsat/iosbuild/Debug-iphonesimulator/libUnfiltered\ Audio\ Bass\ Mint.a -framework AudioUnit -framework AVFoundation -framework Accelerate -framework AudioToolbox -framework CoreAudio -framework CoreAudioKit -framework CoreGraphics -framework CoreImage -framework CoreMIDI -framework CoreText -framework Foundation -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework UIKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/tricky/Code/uamaster/projects/lowsat/iosbuild/Unfiltered\ Audio\ Bass\ Mint.build/Debug-iphonesimulator/Unfiltered_Audio_Bass_Mint_AUv3_AppExtension.build/Unfiltered\ Audio\ Bass\ Mint.appex-Simulated.xcent -Xlinker -dependency_info -Xlinker /Users/tricky/Code/uamaster/projects/lowsat/iosbuild/Unfiltered\ Audio\ Bass\ Mint.build/Debug-iphonesimulator/Unfiltered_Audio_Bass_Mint_AUv3_AppExtension.build/Objects-normal/x86_64/Unfiltered\ Audio\ Bass\ Mint_dependency_info.dat -o /Users/tricky/Code/uamaster/projects/lowsat/iosbuild/Debug-iphonesimulator/Unfiltered\ Audio\ Bass\ Mint.appex/Unfiltered\ Audio\ Bass\ Mint

> ld: framework not found AudioUnit
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by McMartin** [comment]
Hi @mhetrick,

Thanks a lot for reporting these 2 issues: they are both bugs in FRUT 😅 

I opened https://github.com/McMartin/FRUT/pull/636 to fix them.

**Comment by mhetrick** [comment]
@McMartin Wow, thanks! That was fast. That branch fixes both issues for me.
