### ISSUE TITLE
Can't convert JUCE 6.0.0 projects without .jucer file modification

### ISSUE THREAD

**Issue by E-Fir** [McMartin/FRUT#649]
Jucer2CMake exits with the "is not a valid Jucer project" error for all my projects.
After debugging the FRUT, I have figured out that the jucer file is lack of the "jucerVersion" attribute in the root node.
Adding `jucerVersion="6.0.0"` to the root node resolves the issue.

**Comment by McMartin** [comment]
@E-Fir thanks a lot for opening this issue and reporting this bug!
I opened https://github.com/McMartin/FRUT/pull/650, which should fix it.
