### ISSUE TITLE
Company name missing from JuceHeader

### ISSUE THREAD

**Issue by benediktsailer** [McMartin/FRUT#680]
Currently the ProjectInfo::companyName field doesn't get added from the Jucer file, when the JuceHeader is generated through FRUT.

**Comment by McMartin** [comment]
@benediktsailer this issue has been fixed by https://github.com/McMartin/FRUT/pull/681. Don't hesitate to open new GitHub issues for any problem/question you might have with FRUT. Please also consider starring the repository to give it more visibility, thanks!
