### ISSUE TITLE
Error by loading CMakeLists.txt to QtCreator

### ISSUE THREAD

**Issue by ArtmanUrgus** [McMartin/FRUT#689]
Hello all,
I load the generated CMakeLists.txt file into QtCreator and get the following message from cmake

```
CMake Error at CMakeLists.txt:9 (include):
  include could not find requested file:

    Reprojucer


CMake Error at CMakeLists.txt:20 (jucer_project_begin):
  Unknown CMake command "jucer_project_begin".
```

An error in the line 
include(Reprojucer)

I'm not very familiar with Cmake, I've only built simple projects before. 
How to add Reprojucer to the project correctly? Obviously cmake can't find the path to it but I'm not sure where is the Reprojucer file or how to add path explicitly?
Thanks in advance for help!

**Comment by McMartin** [comment]
Hi @ArtmanUrgus,

I guess line 8 of that `CMakeLists.txt` file contains
```cmake
# list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/<relative_path_to_FRUT>/cmake")
```
You can uncomment that line (i.e. remove the leading `#` character) and replace `<relative_path_to_FRUT>` with whatever is needed to go from that `CMakeLists.txt` file to the FRUT repository (something like `../FRUT`, `../../FRUT`, or `third-party/FRUT`).

I hope this helps!

**Comment by ArtmanUrgus** [comment]
Thanks for your help McMartin,

your solution helped to eliminate the previous error. Now cmake reports the following problem


CMake` Error at F:/LIBRARIES/FRUT-main/FRUT-main/cmake/Reprojucer.cmake:2135 (message):
  You must call jucer_export_target_configuration("Code::Blocks (Windows)")
  before calling jucer_project_end().
Call Stack (most recent call first):
  CMakeLists.txt:166 `(jucer_project_end)


Adding lines


jucer_export_target("Code::Blocks (Windows)")

jucer_export_target_configuration(
    "Code::Blocks (Windows)"
)


doesn't solve the problem. The message remains the same.

**Comment by ArtmanUrgus** [comment]
OK, I found the solution:

```
jucer_export_target("Code::Blocks (Windows)")

jucer_export_target_configuration(
    "Code::Blocks (Windows)"
    NAME "Debug"
    DEBUG_MODE ON
    BINARY_NAME "MyFirstJUCE_AudioProject"
)

jucer_export_target_configuration(
    "Code::Blocks (Windows)"
    NAME "Release"
    DEBUG_MODE OFF
    BINARY_NAME "MyFirstJUCE_AudioProject"
)
```
Thank you very much again

**Comment by McMartin** [comment]
I'm closing this GitHub issue, since the OP found a solution.
