### ISSUE TITLE
Console Application Reprojucer.cmake bug

### ISSUE THREAD

**Issue by benediktadams** [McMartin/FRUT#709]
Reprojucer.cmake sets `XCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER` when generating the .plist.
But there is no .plist for a Console Application.

This results in the following error, when trying to build a juce CommandLine Application project:
`error: Bundle identifier is missing. ProjectName doesn't have a bundle identifier. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor. (in target 'ProjectName' from project 'ProjectName')`

**Comment by McMartin** [comment]
@benediktadams thanks for reporting! I'll work on fixing this ASAP.

Out of curiosity, which version of Xcode are you using? I tried to reproduce the issue, but I could only try with Xcode 12.2 on macOS 10.15 Catalina.

**Comment by benediktadams** [comment]
@McMartin I'm on macOS 11.6.2 and XCode 13.2.1 

I can confirm this fixed it :) Thank you
