### ISSUE TITLE
CMake error when building the project

### ISSUE THREAD

**Issue by VedantKalbag** [McMartin/FRUT#716]
After following the build instructions in the getting started, I am able to generate the CMakeLists.txt file, however when building this file, I get the following error:
CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:72 (jucer_project_module)
  
  
  I am using JUCE v.6.1.5 in CLion and the latest version of FRUT

**Comment by McMartin** [comment]
Hi @VedantKalbag,

Thank you very much for using FRUT!

I looked into your issue, and I can't really explain what is happening... It seems that `Reprojucer_data_DIR` is set to `plugin_framework/GuitarAmpPlugin`, when it should actually be `plugin_framework/FRUT/cmake/data`.

Could you please attach your `CMakeLists.txt` file to a new comment? Feel free to remove or anonymize any confidential data.

**Comment by VedantKalbag** [comment]
Here you go!
Thanks for looking into it so soon!
[CMakeLists.txt](https://github.com/McMartin/FRUT/files/8092533/CMakeLists.txt)

**Comment by McMartin** [comment]
That `CMakeLists.txt` looks perfectly fine 😄 

Could you please attach the `CMakeCache.txt` file to a new comment? That file is written by CMake itself and is located at the root of the binary directory.

**Comment by VedantKalbag** [comment]
Here's the CMakeCache.txt file from the <root>/GuitarAmpPlugin/build directory (there is no other such file in the project folder)
[CMakeCache.txt](https://github.com/McMartin/FRUT/files/8092751/CMakeCache.txt)

Additional info that may be useful:
After running "../FRUT/prefix/FRUT/bin/Jucer2CMake reprojucer GuitarAmpPlugin.jucer ../FRUT/prefix/FRUT/cmake/Reprojucer.cmake", the file that I shared in the comment above is generated.


I then ran "cmake .. -G Xcode" from <root>/GuitarAmpPlugin/build and I got this message: 
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:72 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:77 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:93 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:103 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:103 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:103 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:103 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:103 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:103 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:103 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:114 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:124 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:131 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:147 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:152 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:162 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:168 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:176 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceLibraryCode-Wrapper.cpp.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:557 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:188 (jucer_project_module)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JucePluginDefines.h.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:3831 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:2254 (_FRUT_generate_AppConfig_and_JucePluginDefines_header)
  CMakeLists.txt:214 (jucer_project_end)


CMake Error: File /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/data/JuceHeader.h.in does not exist.
CMake Error at /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:4093 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:2255 (_FRUT_generate_JuceHeader_header)
  CMakeLists.txt:214 (jucer_project_end)


-- Configuring incomplete, errors occurred!
See also "/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/build/CMakeFiles/CMakeOutput.log".

**Comment by McMartin** [comment]
Hi @VedantKalbag,

Thanks for sharing the `CMakeCache.txt` file and the complete CMake output. Unfortunately, I couldn't find anything suspicious there as well 😅 

But I haven't said my last word! Could you please try running
```
cmake .. -G Xcode --trace-expand 2> trace-log.txt
```
inside the `/GuitarAmpPlugin/build` directory and attach the resulting `trace-log.txt` file in a new comment? That file will contain every single command that CMake runs, with all variables expanded. That should hopefully help me understand what is going on. Thanks!

**Comment by VedantKalbag** [comment]
Here you go!
[trace-log.txt](https://github.com/McMartin/FRUT/files/8099060/trace-log.txt)

Thanks again for taking a look at this!

**Comment by VedantKalbag** [comment]
-- A: CMAKE_CURRENT_LIST_FILE = /Users/vedant/Downloads/check_CURRENT_LIST_vars/CMakeLists.txt
-- B: CMAKE_CURRENT_LIST_DIR = /Users/vedant/Downloads/check_CURRENT_LIST_vars
-- C: CMAKE_CURRENT_LIST_FILE = /Users/vedant/Downloads/check_CURRENT_LIST_vars/prefix/FRUT/cmake/Reprojucer.cmake
-- D: CMAKE_CURRENT_LIST_DIR = /Users/vedant/Downloads/check_CURRENT_LIST_vars/prefix/FRUT/cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vedant/Downloads/check_CURRENT_LIST_vars/build
[CMakeCache.txt](https://github.com/McMartin/FRUT/files/8099415/CMakeCache.txt)

**Comment by McMartin** [comment]
So CMake works in this simple case.

Could you please make an archive from `/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix` (called `prefix.zip`) and attach it in a new comment?

**Comment by VedantKalbag** [comment]
Here you go!
[prefix.zip](https://github.com/McMartin/FRUT/files/8099722/prefix.zip)

**Comment by McMartin** [comment]
Two lines of `/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/prefix/FRUT/cmake/Reprojucer.cmake` are different from the original:
- line 36 is `set(Reprojucer.cmake_DIR ".")`, while the original is `set(Reprojucer.cmake_DIR "${CMAKE_CURRENT_LIST_DIR}")`
- line 93 is `set(JUCER_PROJECT_DIR "." PARENT_SCOPE)`, while the original is `set(JUCER_PROJECT_DIR "${CMAKE_CURRENT_SOURCE_DIR}" PARENT_SCOPE)`

Did you make these changes yourself?
Did you maybe first make the changes on `/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/FRUT/cmake/Reprojucer.cmake`?

**Comment by VedantKalbag** [comment]
This is strange, I haven't changed any files myself. Let me try setting these back to the original lines and try again

**Comment by VedantKalbag** [comment]
```
FAILED: CMakeFiles/GuitarAmpPlugin_Shared_Code.dir/Source/PluginEditor.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DDEBUG=1 -DJUCE_DISPLAY_SPLASH_SCREEN=1 -DJUCE_GLOBAL_MODULE_SETTINGS_INCLUDED=1 -DJUCE_MODULE_AVAILABLE_juce_audio_basics=1 -DJUCE_MODULE_AVAILABLE_juce_audio_devices=1 -DJUCE_MODULE_AVAILABLE_juce_audio_formats=1 -DJUCE_MODULE_AVAILABLE_juce_audio_plugin_client=1 -DJUCE_MODULE_AVAILABLE_juce_audio_processors=1 -DJUCE_MODULE_AVAILABLE_juce_audio_utils=1 -DJUCE_MODULE_AVAILABLE_juce_core=1 -DJUCE_MODULE_AVAILABLE_juce_data_structures=1 -DJUCE_MODULE_AVAILABLE_juce_dsp=1 -DJUCE_MODULE_AVAILABLE_juce_events=1 -DJUCE_MODULE_AVAILABLE_juce_graphics=1 -DJUCE_MODULE_AVAILABLE_juce_gui_basics=1 -DJUCE_MODULE_AVAILABLE_juce_gui_extra=1 -DJUCE_REPORT_APP_USAGE=1 -DJUCE_SHARED_CODE=1 -DJUCE_STANDALONE_APPLICATION=JucePlugin_Build_Standalone -DJUCE_STRICT_REFCOUNTEDPOINTER=1 -DJUCE_USE_DARK_SPLASH_SCREEN=1 -DJUCE_VST3_CAN_REPLACE_VST2=0 -DJucePlugin_AAXCategory=0 -DJucePlugin_AAXDisableBypass=0 -DJucePlugin_AAXDisableMultiMono=0 -DJucePlugin_AAXIdentifier=com.LL.GuitarAmpPlugin -DJucePlugin_AAXManufacturerCode=JucePlugin_ManufacturerCode -DJucePlugin_AAXProductId=JucePlugin_PluginCode -DJucePlugin_AUExportPrefix=GuitarAmpPluginAU -DJucePlugin_AUExportPrefixQuoted=\"GuitarAmpPluginAU\" -DJucePlugin_AUMainType="'aufx'" -DJucePlugin_AUManufacturerCode=JucePlugin_ManufacturerCode -DJucePlugin_AUSubType=JucePlugin_PluginCode -DJucePlugin_Build_AAX=0 -DJucePlugin_Build_AU=1 -DJucePlugin_Build_AUv3=0 -DJucePlugin_Build_RTAS=0 -DJucePlugin_Build_Standalone=1 -DJucePlugin_Build_Unity=0 -DJucePlugin_Build_VST3=1 -DJucePlugin_Build_VST=0 -DJucePlugin_CFBundleIdentifier=com.LL.GuitarAmpPlugin -DJucePlugin_Desc=\"GuitarAmpPlugin\" -DJucePlugin_EditorRequiresKeyboardFocus=0 -DJucePlugin_Enable_IAA=0 -DJucePlugin_IAAName="\"LL: GuitarAmpPlugin\"" -DJucePlugin_IAASubType=JucePlugin_PluginCode -DJucePlugin_IAAType="0x61757278 // 'aurx'" -DJucePlugin_IsMidiEffect=0 -DJucePlugin_IsSynth=0 -DJucePlugin_Manufacturer=\"LL\" -DJucePlugin_ManufacturerCode="0x4d616e75 // 'Manu'" -DJucePlugin_ManufacturerEmail=\"\" -DJucePlugin_ManufacturerWebsite=\"\" -DJucePlugin_Name=\"GuitarAmpPlugin\" -DJucePlugin_PluginCode="0x556f7462 // 'Uotb'" -DJucePlugin_ProducesMidiOutput=0 -DJucePlugin_RTASCategory=0 -DJucePlugin_RTASDisableBypass=0 -DJucePlugin_RTASDisableMultiMono=0 -DJucePlugin_RTASManufacturerCode=JucePlugin_ManufacturerCode -DJucePlugin_RTASProductId=JucePlugin_PluginCode -DJucePlugin_VSTCategory=kPlugCategEffect -DJucePlugin_VSTNumMidiInputs=16 -DJucePlugin_VSTNumMidiOutputs=16 -DJucePlugin_VSTUniqueID=JucePlugin_PluginCode -DJucePlugin_Version=1.0.0 -DJucePlugin_VersionCode=0x10000 -DJucePlugin_VersionString=\"1.0.0\" -DJucePlugin_Vst3Category=\"Fx\" -DJucePlugin_WantsMidiInput=0 -D_DEBUG=1 -I/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/cmake-build-debug/JuceLibraryCode -I/Users/vedant/Desktop/Programming/JUCE/modules -I/Users/vedant/Desktop/Programming/JUCE/modules/juce_audio_processors/format_types/VST3_SDK -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -stdlib=libc++ -mmacosx-version-min=10.11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -std=c++14 -MD -MT CMakeFiles/GuitarAmpPlugin_Shared_Code.dir/Source/PluginEditor.cpp.o -MF CMakeFiles/GuitarAmpPlugin_Shared_Code.dir/Source/PluginEditor.cpp.o.d -o CMakeFiles/GuitarAmpPlugin_Shared_Code.dir/Source/PluginEditor.cpp.o -c /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/PluginEditor.cpp
In file included from /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/PluginEditor.cpp:10:
In file included from /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/PluginEditor.h:11:
/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/cmake-build-debug/JuceLibraryCode/JuceHeader.h:34:24: error: redefinition of 'projectName'
    const char* const  projectName    = "GuitarAmpPlugin";
                       ^
/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/../JuceLibraryCode/JuceHeader.h:44:24: note: previous definition is here
    const char* const  projectName    = "GuitarAmpPlugin";
                       ^
In file included from /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/PluginEditor.cpp:10:
In file included from /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/PluginEditor.h:11:
/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/cmake-build-debug/JuceLibraryCode/JuceHeader.h:35:24: error: redefinition of 'companyName'
    const char* const  companyName    = "LL";
                       ^
/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/../JuceLibraryCode/JuceHeader.h:45:24: note: previous definition is here
    const char* const  companyName    = "LL";
                       ^
In file included from /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/PluginEditor.cpp:10:
In file included from /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/PluginEditor.h:11:
/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/cmake-build-debug/JuceLibraryCode/JuceHeader.h:36:24: error: redefinition of 'versionString'
    const char* const  versionString  = "1.0.0";
                       ^
/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/../JuceLibraryCode/JuceHeader.h:46:24: note: previous definition is here
    const char* const  versionString  = "1.0.0";
                       ^
In file included from /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/PluginEditor.cpp:10:
In file included from /Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/PluginEditor.h:11:
/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/cmake-build-debug/JuceLibraryCode/JuceHeader.h:37:24: error: redefinition of 'versionNumber'
    const int          versionNumber  = 0x10000;
                       ^
/Users/vedant/Desktop/Programming/MUSI6106-Project/plugin_framework/GuitarAmpPlugin/Source/../JuceLibraryCode/JuceHeader.h:47:24: note: previous definition is here
    const int          versionNumber  = 0x10000;
                       ^
4 errors generated.
[17/19] Building CXX object CMakeFiles/GuitarAmpPlugin_Shared_Code.dir/JuceLibraryCode/include_juce_gui_basics.mm.o
ninja: build stopped: subcommand failed.
```

**Comment by McMartin** [comment]
This seems to be an occurrence of the problem I described in https://github.com/McMartin/FRUT/issues/573#issuecomment-573748075.

Please replace any line like
```cpp
#include "../JuceLibraryCode/JuceHeader.h"
```
with
```cpp
#include <JuceHeader.h>
```

**Comment by VedantKalbag** [comment]
That has fixed it, thank you for all your help!

**Comment by McMartin** [comment]
I'm glad you got it working 🙂 
Feel free to open a new GitHub issue if you have any problem or question.
