### ISSUE TITLE
Bug: Cannot compile Windows VST3 target: Extra strings get inserted in VST3's .vcxproj

### ISSUE THREAD

**Issue by SuganthanBC** [McMartin/FRUT#721]
Problem: When converting a jucer project(JUCE 6.1.5) to cmake via FRUT reprojucer and compiling VST3 target ended up some syntax errors in the juce's VST3_Wrapper header file.

Martin suggested to compare FRUT reprojucer generated VST3.vcxproj with the one generated by projucer after which I found that in certain places of reprojucer generated VST3.vcxproj, the entries JucePlugin_ManufacturerCode, JucePlugin_PluginCode, etc had extra strings(" // ABCD") along with their corresponding hex values.

After removing those extra strings, the build compiled just fine.

PS: VST target also suffered the similar problem

![temp](https://user-images.githubusercontent.com/5999762/158966392-645d40cd-26dc-4aa6-af0b-8c0f88410029.png)

**Comment by McMartin** [comment]
@SuganthanBC Thanks a lot for finding and reporting that bug! I'll take care of fixing it ASAP.
