### ISSUE TITLE
JUCE 7 causing "Undefined symbols for architecture x86_64"

### ISSUE THREAD

**Issue by jdh9862** [McMartin/FRUT#742]
I recently updated to JUCE 7, and began getting this error when I try to build with CLion using CMake
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MTLTextureDescriptor", referenced from:
      objc-class-ref in libBasic.a(include_juce_gui_basics.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

From a little digging, I think something is up with how FRUT is generating the CMake file. I am still able to build/run my code with Xcode using Projucer.

**Comment by McMartin** [comment]
@jdh9862 thanks for using FRUT!

Basic support for JUCE 7 was added in https://github.com/McMartin/FRUT/pull/724, which was merged 19 days ago. Which commit of FRUT are you using?

**Comment by jdh9862** [comment]
I am at the head of main. I see the commit you are referring to, but I am still experiencing this issue. I have tried deleting  `CMakeLists.txt` and `cmake-build-debug` to try to get a clean build, but the error is persisting.

**Comment by McMartin** [comment]
@jdh9862 Could you please add these two lines to your `CMakeLists.txt` file (after the line that contains `include(Reprojucer)`):
```cmake
file(SHA1 "${Reprojucer.cmake_DIR}/Reprojucer.cmake" reprojucer_hash)
message(STATUS "Reprojucer.cmake's hash is: ${reprojucer_hash}")
```
and tell me what `Reprojucer.cmake`'s hash is? 
Thanks!

**Comment by jdh9862** [comment]
`-- Reprojucer.cmake's hash is: 5ac16e71c903c33f9331c81d8910728d7112d0d0`

**Comment by McMartin** [comment]
@jdh9862 I'm sorry, I edited my previous comment and changed the second line to add. Could you please edit your CMakeLists.txt to match and give me the output?

**Comment by jdh9862** [comment]
`-- 5ac16e71c903c33f9331c81d8910728d7112d0d0  /Users/jameshindal/FRUT/prefix/FRUT/cmake/Reprojucer.cmake`

**Comment by McMartin** [comment]
@jdh9862 `FRUT/prefix/FRUT/cmake/Reprojucer.cmake` was copied from `FRUT/cmake/Reprojucer.cmake` when you ran `cmake --build . --target install` inside of `FRUT/build`. The files under `FRUT/prefix` don't get updated by checking out a different commit.

You either need to:
1. update all the files that are located under `FRUT/prefix` by running
   ```
   cd FRUT/build
   cmake --build . --target install
   ```

2. use `FRUT/cmake/Reprojucer.cmake` in your `CMakeLists.txt` by changing the line
```diff
-list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/../FRUT/prefix/FRUT/cmake")
+list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/../FRUT/cmake")
 include(Reprojucer)
```

**Comment by jdh9862** [comment]
That fixed everything, thank you :)
