### ISSUE TITLE
Trailing whitespace bug on JUCEOPTIONS definitons in modules

### ISSUE THREAD

**Issue by benediktadams** [McMartin/FRUT#747]
Defining a config option in a module like the following can break, if the config name has trailing whitespace (so some space behind `Config: SomeOption`. This results in the config not being translated to CMakeLists.txt properly by Reprojucer and instead always showing up commented out in the CMakeLists.txt, no matter what it's actually set to in Projucer. 

```
/** Config: SomeOption
          This is an option for a custom JUCE module
*/
#ifndef SomeOption
#define SomeOption 0
#endif
```

will end up in the CMakeLists.txt as 

`# SomeOption`
instead of 
`SomeOption ON`

even though it's set to `Enabled` in Projucer.

This happens, if there's trailing whitespace on `/** Config: SomeOption   `.

The code handling this is here: 
https://github.com/McMartin/FRUT/blob/60fd0f15727ddfb7384318c300a392397598280f/Jucer2CMake/src/reprojucer.hpp#L1274  

Ideally reprojucer wouldn't care about trailing whitespace, as C++ users are not generally used to regard these things

**Comment by McMartin** [comment]
@benediktadams Thanks a lot for finding and reporting this bug! It should be resolved by https://github.com/McMartin/FRUT/pull/748.
